.TH motif 1 "January 28th 2026" "motif-0.1.0"
.SH NAME
motif \- a simple wallpaper utility for theming software.
.SH SYNOPSIS
.B motif 
[\fI\-\-help\fR] [\fI\-\-version\fR] [\fIfile_path\fR]
.SH DESCRIPTION
Motif is a wallpaper utility that sets the wallpaper, and places a derived color scheme in \fI$HOME/.motif.colors\fR.
.SH OPTIONS
.B -h, --help
    Shows a help message, and exits.

.B -v, --version
    Prints the version, and exits.
.SH BUGS
Early development; expect quirks and rough edges. If you find it, chances are, so have I.
.SH AUTHOR
Written by cookiiq <\fIxenith.contact.mail@gmail.com\fR>
.SH SEE ALSO
\fIFEH\fR(1) \- Default utility used to render wallpapers

\fIWAL\fR(1) \- A similar utility to motif.